// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTFAL9ISBnYxcpKhrhFArhOGLdY-8eiLE',
    appId: '1:114433562464:web:457d53d549597f5f39f005',
    messagingSenderId: '114433562464',
    projectId: 'escopay-7b5b7',
    authDomain: 'escopay-7b5b7.firebaseapp.com',
    storageBucket: 'escopay-storage',
    measurementId: 'G-CSQSXCXVPJ',
  );
}
